#%RAML 1.0 NamedExample
{
  "statusCode": "400",
  "apiInError" : "some-api",
  "flowInError" : "flow-name",
  "correlationId" : "e4c01q",
  "error": {
    "type": "APIKIT:<>",
    "detail": "The user was missing required fields"
  }
}