#%RAML 1.0 NamedExample
branch-list-response-example:
  {
    "branchList": 
    [
      {
        "branchId" : 99,
        "branchType" : "Home Branch",
        "branchLogo" : "https://www.example.org/images/logo.png",
        "branchCode" : "RFMAY",
        "branchName" : "RFD SHINGLES - MAYBERRY",
        "branchAddress" : "123 Main St",
        "branchCityStateZip": "Mayberry, NC 27031",
        "branchFax" : "123-555-1212",
        "branchPhone" : "123-555-1213",
        "latitude" : -96.682624,
        "longitude" : 33.145384,
        "businessHours" : "Monday - Friday, 7:00 AM to 5:00 PM",
        "saturdayBusinessHours" : "7:00 AM to 1:00 PM"
      }
    ]
  }