#%RAML 1.0 NamedExample
brand-response-example:
  {
    "brandList": 
    [
      {
        "brandId" : 19,
        "brandLogo" : "https://media.srsdistribution.com/Uploads/BrandsByID/19.png",
        "brandName" : "SUPERIOR DISTRIBUTION",
      },
      {
        "brandId" : 18,
        "brandLogo" : "https://media.srsdistribution.com/Uploads/Brands/SuncoastRoofing-18.png",
        "brandName" : "SUNCOAST",
      },
      {
        "brandId" : 29,
        "brandLogo" : "https://media.srsdistribution.com/Uploads/Brands/AdvancedRoofingSupply-29.png",
        "brandName" : "ADVANCED BUILDING PRODUCTS",
      }
    ]
  }