#%RAML 1.0 NamedExample
{
  "branchLogo" : "https://www.example.org/images/logo.png",
  "branchId": 99,
  "branchCode" : "RFMAY",
  "branchName" : "RFD SHINGLES - MAYBERRY",
  "branchAddress" : "123 Main St",
  "branchCity": "Mayberry",
  "branchState": "NC",
  "branchZip": "12345",
  "branchCityStateZip": "Mayberry, NC 12345",
  "branchFax" : "123-555-1212",
  "branchPhone" : "123-555-1213",
  "branchManager" : "Opie Taylor",
  "branchManagerEmail": "otaylor@example.org",
  "businessHours" : "Monday -Friday, 7:30 AM to 4:30 PM",
  "saturdayBusinessHours" : "7:00 AM to 1:00 PM",
  "branchRegion": "SOUTHEAST",
  "branchRegionId": 1,
  "longitude": -96.682624,
  "latitude": 33.145384
}