#%RAML 1.0 NamedExample
nearest-eligible-branch-example:
  {
    "customerNearestBranchList":  [
      {
          "branchId" : 100,
          "branchCd" : "RFMAY",
          "description" : "SRS DISTRIBUTION",
          "brandName" : "SOUTHERN SHINGLES",
          "address1" : "5900 Lake Forest Dr",
          "city" : "McKinney",
          "state" : "TX",
          "zip" : "12345",
          "phone" : "234-555-9878",
          "branchManagerName" : "Johnny Smith",
          "branchManagerEmailAddress" : "jsmith@example.com",
          "branchLatitude" : 12.090934,
          "branchLongitude" : -12.903457,
          "distance" : 23.3452
      },
      {
          "branchId" : 101,
          "branchCd" : "SRLEW",
          "description" : "SRS DISTRIBUTION",
          "brandName" : "SUNCOASE ROOFING SUPPLY",
          "address1" : "123 Main St",
          "city" : "Lewisville",
          "state" : "TX",
          "zip" : "54321",
          "phone" : "111-555-2222",
          "branchManagerName" : "Jenny Smitty",
          "branchManagerEmailAddress" : "jsmitty@example.com",
          "branchLatitude" : 33.333,
          "branchLongitude" : -97.865,
          "distance" : 10.0001
      }
    ]
  }