
package hello;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-11-14T15:09:30.531-06:00
 * Generated source version: 2.7.18
 * 
 */
public final class HelloWorldService_HelloWorldServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://muleesbcxfsoapexpose.huongdanjava.com/", "HelloWorldServiceService");

    private HelloWorldService_HelloWorldServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldServiceService ss = new HelloWorldServiceService(wsdlURL, SERVICE_NAME);
        HelloWorldService port = ss.getHelloWorldServicePort();  
        
        {
        System.out.println("Invoking hello...");
        hello.Hello _hello_parameters = null;
        java.lang.String _hello_clientIdVal = "";
        javax.xml.ws.Holder<java.lang.String> _hello_clientId = new javax.xml.ws.Holder<java.lang.String>(_hello_clientIdVal);
        hello.HelloResponse _hello__return = port.hello(_hello_parameters, _hello_clientId);
        System.out.println("hello.result=" + _hello__return);

        System.out.println("hello._hello_clientId=" + _hello_clientId.value);

        }

        System.exit(0);
    }

}
