#%RAML 1.0 NamedExample
{
  "statusCode": "405",
  "apiInError" : "some-api",
  "flowInError" : "flow-name",
  "correlationId" : "e4c01q",
  "error": {
    "type": "APIKIT:<>",
    "detail": "Method not allowed"
  }
}