#%RAML 1.0 DataType
description: Base product for searching
type: object
properties:
  id:
    type: number
    required: true
    example: 801
  name:
    type: string
    example: "Jeep Wrangler"
  summary:
    type: string
    example: "A Jeep Wrangler."
  manufacturer:
    type: string
    example: "Jeep"
