#%RAML 1.0 NamedExample
{
  "muleProperties": {
    "muleRuntime": "3.9.3",
    "apiName": "health-check-api",
    "version": "v1:15800951",
    "server": "AC0084",
    "ip": "172.27.112.1",
    "timeZone": "America/Chicago",
    "environment": "dev"
  },
  "jvmProperties": {
    "pid": "29108@AC0084",
    "vmName": "Java HotSpot(TM) 64-Bit Server VM",
    "vmVendor": "Oracle Corporation",
    "vmVersion": "1.8.0_231",
    "locale": "English (United States)",
    "memory": {
      "heapMemoryUsage": {
        "init": "264241152(258048K)",
        "used": "382810496(373838K)",
        "committed": "1030225920(1006080K)",
        "max": "3756523520(3668480K)"
      },
      "nonHeapMemoryUsage": {
        "init": "2555904(2496K)",
        "used": "114860400(112168K)",
        "committed": "116654080(113920K)",
        "max": "-1(-1K)"
      }
    },
    "threadCount": {
      "activeThreadCount": 64,
      "daemonThreadCount": 49
    },
    "garbageCollection": [
      {
        "gcName": "PS Scavenge",
        "collectionCount": 19,
        "collectionTime": 292
      },
      {
        "gcName": "PS MarkSweep",
        "collectionCount": 3,
        "collectionTime": 473
      },
      {
        "gcName": "PS Scavenge",
        "collectionCount": 19,
        "collectionTime": 292
      },
      {
        "gcName": "PS MarkSweep",
        "collectionCount": 3,
        "collectionTime": 473
      },
      {
        "gcName": "PS Scavenge",
        "collectionCount": 19,
        "collectionTime": 292
      },
      {
        "gcName": "PS MarkSweep",
        "collectionCount": 3,
        "collectionTime": 473
      }
    ]
  },
  "osProperties": {
    "osName": "Windows 10",
    "osVersion": "10.0",
    "osArchitechture": "amd64",
    "systemLoadAverage": -1.0,
    "availableProcessors": 12
  },
  "timestamp": "2019-11-22T15:11:46.375-06:00",
  "correlationId" : "648c5fb2-0d74-11ea-9dab-105bad3268d7"
}