#%RAML 1.0 NamedExample
{
  "status" : "OK",
  "timestamp" : "2019-07-30T09:30:10Z",
  "appName" : "health-check-api",
  "hostname" : "https://health-check-api-dev.us-w2.cloudhub.io",
  "systemStatus" : 
    [
      {
        "systemName" : "SQLServer",
        "connectionConfig" : "10.88.151.91:1433",
        "user" : "admin",
        "status" : "OK",
        "timestamp" : "2019-07-30T09:30:10Z"
      },
      {
        "systemName" : "Amazon S3",
        "connectionConfig" : "N/A",
        "user" : "N/A",
        "status" : "OK",
        "timestamp" : "2019-07-30T09:30:10Z"
      }
    ]
}