#%RAML 1.0 NamedExample
order-template-response-example:
  {
    "BRANCH_USER_ID": "253_44292",
    "USER_ID": "44292",
    "BRANCH_ID": "253",
    "TEMPLATES": [
        {
            "TEMPLATE_MODEL": "Order History",
            "TEMPLATES": [
                {
                    "CREATION_TIME": 1572912622,
                    "TEMPLATE_NUMBER": 1,
                    "TEMPLATE": {
                        "Shingles": "CT LANDMARK AR 3 BD/SQ",
                        "Hip and Ridge": "CT SHADOW RIDGE AR 30'/BD",
                        "Underlayment": "TOP SHIELD SECUREGRIP 25 SYNTH UDL 10 SQ/RL",
                        "Starter": "CT SWIFTSTART STARTER 116'/BD",
                        "Ice and Water": "RESISTO EAVE PROTECTOR 36\" X 65' 2 SQ/RL",
                        "Vents": "AIR VENT SHINGLEVENT II W/NAILS 12\" X 4'",
                        "Caulk": "",
                        "Spray Paint": "TOP SHIELD SHNGL/FLASHG AEROSOL 12.0 OZ",
                        "Drip Edge": "BERGER F5M ALUMINUM DRIP EDGE 10' .016",
                        "Plastic Caps": "",
                        "Other Fasteners": "",
                        "Coil Nails": "EG COIL ROOFING NAIL 1-1/4\"",
                        "Pipe Flashing": "ALUM PIPE COLLAR PAINTED 3\" - 4\"",
                        "Other Flashing Metal": "VELUX EDL C06 FLASHING KIT EDL C06",
                        "Decking": "OSB 7/16\" 4' x 8'",
                        "W-Valley": "QA ALUMINUM W-VALLEY 18\" X 10' .022",
                        "Gutter Apron": ""
                    },
                    "TEMPLATE_KEY": "templates/order-history/payloads/253_44292/versions/1572912622/template_1.json"
                }
            ]
        },
        {
            "TEMPLATE_MODEL": "Branch Order History",
            "TEMPLATES": [
                {
                    "CREATION_TIME": 1572912622,
                    "TEMPLATE_NUMBER": 1,
                    "TEMPLATE": {
                        "Shingles": "GAF TIMBERLINE HD AR 3 BD/SQ",
                        "Hip and Ridge": "GAF SEAL-A-RIDGE 12\" 25'/BD",
                        "Underlayment": "INTERWRAP RHINO U20 10 SQ/RL",
                        "Starter": "GAF PRO START 120.33'/BD",
                        "Ice and Water": "RESISTO EAVE PROTECTOR 36\" X 65' 2 SQ/RL",
                        "Vents": "GAF COBRA SNOW COUNTRY ADVANCED 12\"",
                        "Caulk": "GEOCEL CAULK 2300 BLACK 10.3 OZ",
                        "Spray Paint": "PAINT 12 OZ",
                        "Drip Edge": "BERGER F5M ALUMINUM DRIP EDGE 10' .016",
                        "Plastic Caps": "STINGER STAPLEPAC PLASTIC CAP STAPLES 5/8\" 2M",
                        "Other Fasteners": "NAT STINGER PAC NAIL 1\" 2000/BX",
                        "Coil Nails": "EG COIL ROOFING NAIL 1-1/4\"",
                        "Pipe Flashing": "ALUM PIPE COLLAR PAINTED 3\" - 4\"",
                        "Other Flashing Metal": "VELUX EDL C06 FLASHING KIT EDL C06",
                        "Decking": "OSB 7/16\" 4' x 8'",
                        "W-Valley": "QA ALUMINUM W-VALLEY 18\" X 10' .022",
                        "Gutter Apron": ""
                    },
                    "TEMPLATE_KEY": "templates/branch-order-history/payloads/253/versions/1572912622/template_1.json"
                }
            ]
        }
    ],
    "ITEMS": [
        {
            "CATEGORY_NAME": "Pipe Flashing",
            "ITEMS": [
                {
                    "ITEM_ID": "9e5f4a9837f204d7e7a673faac7e33be",
                    "ITEM_GENERIC_DESC": "ALUM PIPE COLLAR PAINTED 3\" - 4\"",
                    "PROBABILITY": "0.7",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch"
                },
                {
                    "ITEM_ID": "124f010ea6e376d75f1b3fd34f465548",
                    "ITEM_GENERIC_DESC": "ALUM PIPE COLLAR PAINTED 1\" - 3\"",
                    "PROBABILITY": "0.2",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch"
                },
                {
                    "ITEM_ID": "543ad2a4081d2f2717364a7d6ff8c276",
                    "ITEM_GENERIC_DESC": "AIR VENT AIRJAWK SLANT BACK VENT  ",
                    "PROBABILITY": "0.1",
                    "RANK": "3",
                    "ITEM_SOURCE": "branch"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Drip Edge",
            "ITEMS": [
                {
                    "ITEM_ID": "e7b9a61b3ca32a5fa2f558014fa14949",
                    "ITEM_GENERIC_DESC": "BERGER F5M ALUMINUM DRIP EDGE 10' .016",
                    "PROBABILITY": "1",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Starter",
            "ITEMS": [
                {
                    "ITEM_ID": "a043afb70d7150003fcb14045b5b0b90",
                    "ITEM_GENERIC_DESC": "CT SWIFTSTART STARTER 116'/BD",
                    "PROBABILITY": "0.933333",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                },
                {
                    "ITEM_ID": "9ab4161bc9b92749d2d347140966fa23",
                    "ITEM_GENERIC_DESC": "GAF PRO START 120.33'/BD",
                    "PROBABILITY": "0.066667",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Spray Paint",
            "ITEMS": [
                {
                    "ITEM_ID": "f46e7f4e2f7c3c0ccaa209bba9078731",
                    "ITEM_GENERIC_DESC": "TOP SHIELD SHNGL/FLASHG AEROSOL 12.0 OZ",
                    "PROBABILITY": "1",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Hip and Ridge",
            "ITEMS": [
                {
                    "ITEM_ID": "7ffc51d9851f839354bb928cbd1a77ae",
                    "ITEM_GENERIC_DESC": "CT SHADOW RIDGE AR 30'/BD",
                    "PROBABILITY": "0.866667",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                },
                {
                    "ITEM_ID": "cc422989cd0600d0b7fe8482463ceec8",
                    "ITEM_GENERIC_DESC": "GAF SEAL-A-RIDGE 12\" 25'/BD",
                    "PROBABILITY": "0.133333",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Coil Nails",
            "ITEMS": [
                {
                    "ITEM_ID": "f31b91f5cc2c49bd1aa2aa19de530957",
                    "ITEM_GENERIC_DESC": "EG COIL ROOFING NAIL 1-1/4\"",
                    "PROBABILITY": "1",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Underlayment",
            "ITEMS": [
                {
                    "ITEM_ID": "45a993e52c979d5fcac6bb054d334e57",
                    "ITEM_GENERIC_DESC": "TOP SHIELD SECUREGRIP 25 SYNTH UDL 10 SQ/RL",
                    "PROBABILITY": "0.733333",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                },
                {
                    "ITEM_ID": "274475e8e853ab80b77e9f6312cd28ed",
                    "ITEM_GENERIC_DESC": "SECURE GRIP SYNTHETIC 10 SQ/RL",
                    "PROBABILITY": "0.266667",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Shingles",
            "ITEMS": [
                {
                    "ITEM_ID": "54301eb50346ff73226230d03baf0a8c",
                    "ITEM_GENERIC_DESC": "CT LANDMARK AR 3 BD/SQ",
                    "PROBABILITY": "0.733333",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch"
                },
                {
                    "ITEM_ID": "e5e75f644acde54d51992cf6efa82a27",
                    "ITEM_GENERIC_DESC": "GAF TIMBERLINE HD AR 3 BD/SQ",
                    "PROBABILITY": "0.133333",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch"
                },
                {
                    "ITEM_ID": "3057506fdc2bd39156e368b3416e1dbd",
                    "ITEM_GENERIC_DESC": "CT LANDMARK PRO MAX DEF AR 3 BD/SQ",
                    "PROBABILITY": "0.133333",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Other Flashing Metal",
            "ITEMS": [
                {
                    "ITEM_ID": "439166757f4aea919f99eb34e9250ad8",
                    "ITEM_GENERIC_DESC": "VELUX EDL C06 FLASHING KIT EDL C06",
                    "PROBABILITY": "0.5",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                },
                {
                    "ITEM_ID": "c4fe3cd5897243a440a91bb87a2bbb4a",
                    "ITEM_GENERIC_DESC": "BERGER DORMER FLASHING 2-5/8\" X 3\" X10'",
                    "PROBABILITY": "0.5",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch"
                }
            ]
        },
        {
            "CATEGORY_NAME": "W-Valley",
            "ITEMS": [
                {
                    "ITEM_ID": "423e75f2b8991897138fb83eeb11a9a8",
                    "ITEM_GENERIC_DESC": "QA ALUMINUM W-VALLEY 18\" X 10' .022",
                    "PROBABILITY": "1",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Vents",
            "ITEMS": [
                {
                    "ITEM_ID": "b2b68cd120ffe971ed13751c34ee9240",
                    "ITEM_GENERIC_DESC": "AIR VENT SHINGLEVENT II W/NAILS 12\" X 4'",
                    "PROBABILITY": "0.8",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                },
                {
                    "ITEM_ID": "711c136bf5c79cb5d7c9931637bc9844",
                    "ITEM_GENERIC_DESC": "AIR VENT AIR POWER COOL PLUS 1170 CFM",
                    "PROBABILITY": "0.133333",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch-user"
                },
                {
                    "ITEM_ID": "12540f41856d4c1e7a4ba611da860771",
                    "ITEM_GENERIC_DESC": "GAF COBRA SNOW COUNTRY ADVANCED 12\"",
                    "PROBABILITY": "0.066667",
                    "RANK": "3",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Ice and Water",
            "ITEMS": [
                {
                    "ITEM_ID": "72f68f2de7c93a70f6cd632052e1b0ee",
                    "ITEM_GENERIC_DESC": "RESISTO EAVE PROTECTOR 36\" X 65' 2 SQ/RL",
                    "PROBABILITY": "0.714286",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch"
                },
                {
                    "ITEM_ID": "e15214ada8fd218c677a54dcc4659f86",
                    "ITEM_GENERIC_DESC": "CT WINTERGUARD SAND 2 SQ/RL",
                    "PROBABILITY": "0.214286",
                    "RANK": "2",
                    "ITEM_SOURCE": "branch"
                },
                {
                    "ITEM_ID": "79f1e6d8e789e75c60600095bc1610f5",
                    "ITEM_GENERIC_DESC": "GAF WEATHERWATCH 2 SQ/RL",
                    "PROBABILITY": "0.071429",
                    "RANK": "3",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        },
        {
            "CATEGORY_NAME": "Decking",
            "ITEMS": [
                {
                    "ITEM_ID": "6326b08b69b45ee1dd46d64426f1a3a4",
                    "ITEM_GENERIC_DESC": "OSB 7/16\" 4' x 8'",
                    "PROBABILITY": "1",
                    "RANK": "1",
                    "ITEM_SOURCE": "branch-user"
                }
            ]
        }
    ]
}
