git clone git@bitbucket.org:srsdistribution/srs-orders-process-api.git
git clone git@bitbucket.org:srsdistribution/srs-extract-process-api.git
git clone git@bitbucket.org:srsdistribution/srs-directory-process-api.git
git clone git@bitbucket.org:srsdistribution/srs-deliveries-process-api-proxy.git
git clone git@bitbucket.org:srsdistribution/srs-deliveries-process-api.git
git clone git@bitbucket.org:srsdistribution/srs-error-handling-process-api.git
git clone git@bitbucket.org:srsdistribution/srs-branch-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-customers-system-api.git
git clone git@bitbucket.org:srsdistribution/heritage-branch-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-notification-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-orders-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-deliveries-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-invoices-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-print-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-weather-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-image-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-employees-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-hv-orders-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-event-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-directory-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-products-system-api.git
git clone git@bitbucket.org:srsdistribution/srs-document-system-api.git
