#%RAML 1.0 DataType
type: object
description: 
properties:
  init: 
    type: string
    description: 
    example: "264241152(258048K)"
  used:
    type: string
    description: The mule runtime version the application is running on
    example: "382810496(373838K)"
  committed:
    type: string
    description: The mule runtime version the application is running on
    example: "1030225920(1006080K)"
  max:
    type: string
    description: The mule runtime version the application is running on
    example: "3756523520(3668480K)"