#%RAML 1.0 ResourceType
    description: Collection of available <<resourcePathName>> 
    get:
      description: Collection of available <<resourcePathName>> 
      responses:
        200:
          body:
            application/json: