package com.srs.worldview;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-11-14T15:16:58.674-06:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://muleesbcxfsoapexpose.huongdanjava.com/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloWorldService {

    @WebMethod
    @WebResult(name = "helloResponse", targetNamespace = "http://muleesbcxfsoapexpose.huongdanjava.com/", partName = "result")
    public HelloResponse hello(
        @WebParam(partName = "parameters", name = "hello", targetNamespace = "http://muleesbcxfsoapexpose.huongdanjava.com/")
        Hello parameters,
        @WebParam(partName = "clientId", mode = WebParam.Mode.INOUT, name = "clientId", targetNamespace = "http://muleesbcxfsoapexpose.huongdanjava.com/", header = true)
        javax.xml.ws.Holder<java.lang.String> clientId
    );
}
