#%RAML 1.0 DataType
type: object
properties: 
  personId:
    description: Person ID
    type: string
    required: false
    example: b093i001111sjv3Bjx
  personType:
    description: The type of person that's associated 
    type: string
    required: true
    enum:
      - PATIENT
      - EMERGENCY_CONTACT
      - PATIENT_DR
  firstName:
    description: First name of the person
    type: string
    required: true
    example: John
  lastName:
    description: Last name of the person
    type: string
    required: true
    example: Doe
  mi:
    description: Middle initial of the person
    required: false
    type: string
    example: A
    maxLength: 1
  phoneNumber:
    description: The US Phone Number of the person
    required: true
    type: string
    example: "2124321234"
    pattern: ^[2-9]\d{2}\d{3}\d{4}$
  address1:
    description: The first line of the address
    required: true
    example: 123 Main Street
    type: string
    pattern: ^(\d{3,})\s?(\w{0,5})\s([a-zA-Z]{2,30})\s([a-zA-Z]{2,15})\.?\s?(\w{0,5})$
  address2:
    description: The apartment or 2nd address line
    required: false
    example: Apt 2
    type: string
  city:
    description: The city of the address
    required: true
    example: Denver
    type: string
  zipCode:
    description: The zip code of the address
    required: true
    example: "12345"
    pattern: ^[0-9]{5}([\s-]{1}[0-9]{4})?$
  geoLocation:
    description: geo coordinates of address
    required: false
    type: !include ../location/locationDataType.raml
  isNotifyStatus:
    description: opt-in to be notified via sms
    required: true
    example: true
    type: boolean
  timeLastNotfied:
    description: timestamp for last notification being sent out
    type: datetime
    required: false
    example: 2020-02-28T16:41:41.090Z